version: '2'

services:
    app:
        container_name: base_admin
        build:
          context: ./
          dockerfile: development/app.dockerfile
        volumes:
          - ./storage:/var/www/storage
        env_file: '.env.dev'
        environment:
          - "DB_HOST=database"
          - "REDIS_HOST=cache"

    web:
        container_name: nginx_server
        build:
            context: ./
            dockerfile: development/web.dockerfile
        volumes:
            - ./storage/logs/:/var/log/nginx
        ports:
            - 8990:80

    #database:
       # container_name: mysql_database
       # image: mysql:5.7
       # volumes:
        #  - dbdata:/var/lib/mysql
        #environment:
         # - "MYSQL_DATABASE=base_admin_db"
         # - "MYSQL_USER=root"
         # - "MYSQL_PASSWORD=root"
         # - "MYSQL_ROOT_PASSWORD=root"
        # ports:
          # - 8991:3306

    cache:
      image: redis:3.0-alpine

volumes:
    dbdata: